package com.wx.service.user.mapper;

import com.wx.service.user.entity.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @Description: java类作用描述：请输入你对这个类的描述
 * @Author: 作者：lijianguo
 * @CreateDate: 创建日期：2018/4/18 上午9:42
 * @CreateUser: 创建人：lijianguo
 * @Version: 1.0
 **/
public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_user
     *
     * @mbg.generated
     */
    int insert(User user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User user);

    /**
     * 根据用户的名字获取用户的详细信息
     * @Author LJG
     */
    User findByName(String loginName);

    /**
     * @param userId
     * @return
     */
    int deleteById(@Param("userId") long userId);





}
